FROM nginx

WORKDIR /usr/share/nginx/html

COPY /templates/index.html .
COPY /static/images/* static/images/

RUN rm /etc/nginx/conf.d/default.conf

RUN echo "server {" > /etc/nginx/conf.d/nginx.conf \
    && echo "    listen 80;" >> /etc/nginx/conf.d/nginx.conf \
    && echo "    server_name localhost;" >> /etc/nginx/conf.d/nginx.conf \
    && echo "" >> /etc/nginx/conf.d/nginx.conf \
    && echo "    location / {" >> /etc/nginx/conf.d/nginx.conf \
    && echo "        root /usr/share/nginx/html;" >> /etc/nginx/conf.d/nginx.conf \
    && echo "        index index.html;" >> /etc/nginx/conf.d/nginx.conf \
    && echo "        try_files \$uri \$uri/ =404;" >> /etc/nginx/conf.d/nginx.conf \
    && echo "    }" >> /etc/nginx/conf.d/nginx.conf \
    && echo "}" >> /etc/nginx/conf.d/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
