version: '3'
services:
  apache-container:
    image: apache-image
    container_name: web-apache
    ports:
      - "1010:80"
    networks:
      network-absen:
        ipv4_address: 192.168.5.2

  flask-container:
    image: flask-image
    container_name: web-flask
    ports:
      - "2020:5000"
    networks:
      network-absen:
        ipv4_address: 192.168.5.3

  nginx-container:
    image: nginx-image
    container_name: web-nginx
    ports:
      - "3030:80"
    networks:
      network-absen:
        ipv4_address: 192.168.5.4
networks:
  network-absen:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
