
FROM nginx

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install flask && \
    apt-get clean

RUN mkdir /opt/static
RUN mkdir /opt/static/images

COPY app.py /opt/app.py
COPY /templates/index.html /opt/templates/index.html
COPY /static/images/ /opt/static/images

# Konfigurasi NginX
RUN echo "server {" > /etc/nginx/conf.d/app.conf \
    && echo "    listen 80;" >> /etc/nginx/conf.d/app.conf \
    && echo "    location / {" >> /etc/nginx/conf.d/app.conf \
    && echo "        proxy_pass http://127.0.0.1:5000;" >> /etc/nginx/conf.d/app.conf \
    && echo "        proxy_set_header Host \$host;" >> /etc/nginx/conf.d/app.conf \
    && echo "        proxy_set_header X-Real-IP \$remote_addr;" >> /etc/nginx/conf.d/app.conf \
    && echo "    }" >> /etc/nginx/conf.d/app.conf \
    && echo "}" >> /etc/nginx/conf.d/app.conf

# Memulai NginX
CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
ENV FLASK_APP=/opt/app.py

